{{- if .Values.vaultStaticSecrets.enabled }}
{{- range .Values.vaultStaticSecrets.secrets }}
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: {{ .secretName }}
  namespace: {{ $.Release.Namespace }}
  {{- with $.Values.vaultStaticSecrets.labels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with $.Values.vaultStaticSecrets.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  mount: {{ .mount | default $.Values.vaultStaticSecrets.defaultMount }}
  path: {{ .path }}
  type: {{ .type | default $.Values.vaultStaticSecrets.defaultType }}
  {{- if hasKey . "hmacSecretData" }}
  hmacSecretData: {{ .hmacSecretData }}
  {{- else }}
  hmacSecretData: true
  {{- end }}
  {{- with .refreshAfter }}
  refreshAfter: {{ . }}
  {{- end }}
  {{- if or .vaultAuthRef $.Values.vaultStaticSecrets.defaultVaultAuthRef }}
  vaultAuthRef: {{ .vaultAuthRef | default $.Values.vaultStaticSecrets.defaultVaultAuthRef }}
  {{- end }}
  {{- with .rolloutRestartTargets }}
  rolloutRestartTargets:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  destination:
    create: {{ dig "destination" "create" true . }}
    overwrite: {{ dig "destination" "overwrite" true . }}
    name: {{ dig "destination" "name" .secretName . }}
    {{- with .destination }}
    {{- with .type }}
    type: {{ . }}
    {{- end }}
    {{- with .labels }}
    labels:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with .annotations }}
    annotations:
      {{- tpl (toYaml .) $ | nindent 6 }}
    {{- end }}
    {{- end }}
    {{- if or .includeKeys .excludeKeys .templates }}
    transformation:
      {{- if .includeKeys }}
      includes:
        {{- range .includeKeys }}
        - {{ . }}
        {{- end }}
      {{- end }}
      {{- if .excludeKeys }}
      excludes:
        {{- range .excludeKeys }}
        - {{ . }}
        {{- end }}
      {{- end }}
      {{- if .templates }}
      templates:
        {{- toYaml .templates | nindent 8 }}
      {{- end }}
    {{- end }}
{{- end }}
{{- end }}

